### ISSUE TITLE
Can't deploy a microservice on windows/cygwin

### ISSUE THREAD

**Issue by bmaggi** [PrismTech/agentv#3]
Steps to reproduce
- launch agentv
- launch commander
- try to deploy a microservice

I got the following log 

```
 [CommanderWindow | Debug]:  jarFile = C:\git\iot\agentv\lib\agentv-microsvc-daytime_2.11-0.5.0-SNAPSHOT.jar, nodeId = a
 [Commander | Debug]:  Deploying package agentv-microsvc-daytime_2.11-0.5.0-SNAPSHOT.jar on a
```

but not the success log (that are present for @flefevre on centos)
and also no log in the agentv cygwin

I also tried to restart commander to check that it isn't a refresh problem.

**Comment by kydos** [comment]
@bmaggi, I guess it is again some problem with path separators. I was pretty sure that the File.separator was consistently used to ensure portability, but maybe that is not the case. I'll be able to take a look at this later this PM.

A+

**Comment by kydos** [comment]
@bmaggi, just tested on Windows10 with jdk8 and everything seems to work fine with v.0.5.1. 

A+
