### ISSUE TITLE
Partition Path inconsistent between windows and Unix

### ISSUE THREAD

**Issue by bmaggi** [PrismTech/agentv#5]
The commander is using File.separator to define the partition for micro services
See [Commander.scala](https://github.com/PrismTech/agentv/blob/master/agentv-commander/src/main/scala/com/prismtech/agentv/commander/Commander.scala)

```
class AgentContext(nodeId: String) {
  val microsvcPartition = NodePartition+ File.separator + nodeId
```

The solution might be to create a DDS.separator constant 

Currently: I'm unable to deploy a microservice using commander on windows.
This issue is maybe the root of my problem.

**Comment by kydos** [comment]
Fixed in version 0.5.1

**Comment by bmaggi** [comment]
The version seems to be still 0.5.0-SNAPSHOT:
https://github.com/PrismTech/agentv/tree/master/lib
https://github.com/PrismTech/agentv/blob/master/bin/version

Did I missed something?

**Comment by kydos** [comment]
Maybe I missed a push... Effect of late night and not enough green tea.

Let me check.
