### ISSUE TITLE
Commander should be more CommanderWindow independent

### ISSUE THREAD

**Issue by bmaggi** [PrismTech/agentv#8]
To use [Commander.scala](https://github.com/PrismTech/agentv/blob/master/agentv-commander/src/main/scala/com/prismtech/agentv/commander/Commander.scala) in another context it would be interesting to have it more independent from CommanderWindow 

Especially (from what I understood), it is required to launch the call `def run(window: CommanderWindow)`  method (at least to init the node list L112).

My first tests are working with `Commander.run(new CommanderWindow())` but it may cause some problems on more complicated use cases.

Is it possible to add a new method to "run" the commander without CommanderWindow ?
(or allow to pass null as parameter)

**Comment by kydos** [comment]
The commander was initially intended to be used with the UI. But it could be used by a REPL for agentv. I'll do some refactoring and perhaps add a REPL too.

**Comment by kydos** [comment]
@bmaggi, I've refactored the `Commander` to be independent from the UI. Take a look at the new implementation and at how the `CommanderWindow` leverages it. 

Notice that if you are interested in receiving notification you'll have to implement the interface  `AgentvEventListener`. Also notice that the Commander is no more a Scala Object, it is now a class. 

In any case the take a look at the `CommanderWindow` to get a sense of how you may use the new commander.

**Comment by kydos** [comment]
I am closing the issue as the refactoring addresses it.
