### ISSUE TITLE
Convention naming

### ISSUE THREAD

**Issue by flefevre** [PrismTech/agentv#9]
It seems that your topic name are defined in a class inside "package com.prismtech.agentv / package object prelude"

Would be possible to rename the "package" which is to be a keywoprk for java?
I am not able to reference in a maven project this code due to an error with the compiler.

Thanks

**Comment by kydos** [comment]
That cannot be done as it would break a Scala convention. However, to access the prelude from Java you have to simply use the `package$`. For instance to access the `PartitionSeparator` you'd do:

`com.prismtech.agentv.prelude.package$.MODULE$.PartitionSeparator()`

HTH.
